/**
 * WoW Classic Item API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Slots } from './slots';
import { Source } from './source';


export interface Item { 
    id?: number;
    slot?: Slots;
    name?: string;
    wowHeadId?: number;
    source?: Source;
    own?: boolean;
}

