/**
 * WoW Classic Item API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Slots = 'HEAD' | 'OFFHAND' | 'WRIST' | 'SHOULDERS';

export const Slots = {
    HEAD: 'HEAD' as Slots,
    OFFHAND: 'OFFHAND' as Slots,
    WRIST: 'WRIST' as Slots,
    SHOULDERS: 'SHOULDERS' as Slots
};

