/**
 * WoW Classic Item API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Slots = 'HEAD' | 'NECK' | 'SHOULDERS' | 'BACK' | 'CHEST' | 'WRIST' | 'LEGS' | 'HAND' | 'WAIST' | 'FEET' | 'RING' | 'TRINKET' | 'MAINHAND' | 'OFFHAND' | 'WARD]';

export const Slots = {
    HEAD: 'HEAD' as Slots,
    NECK: 'NECK' as Slots,
    SHOULDERS: 'SHOULDERS' as Slots,
    BACK: 'BACK' as Slots,
    CHEST: 'CHEST' as Slots,
    WRIST: 'WRIST' as Slots,
    LEGS: 'LEGS' as Slots,
    HAND: 'HAND' as Slots,
    WAIST: 'WAIST' as Slots,
    FEET: 'FEET' as Slots,
    RING: 'RING' as Slots,
    TRINKET: 'TRINKET' as Slots,
    MAINHAND: 'MAINHAND' as Slots,
    OFFHAND: 'OFFHAND' as Slots,
    WARD: 'WARD]' as Slots
};

